public class CaseRequestWrapper {
    public CaseRequestWrapper(){
        
    }
    //For mapping input Json parameters
    public String caseOrigin;
    public String dataSource;
    public String priority;
    public String impact;
    public Id accountId;
    public String status;
    public Id contactId;
    public String remedyId;
    public String techSiteId;
    public String title;
    public String caseType1;
    public String caseType2;
    public String caseType3;
    //public String caseType4;
    public String description;
    public String firstName;
    public String lastName;
    public String email;
    public String phone;
    public String queueName;
    public String recordtype;
    public String mcn;
    public String region;
    public String ccList;
    public String notes;
}