/*
*File Name     : CheckFederationIDTest 
* Description   : This class created as a part of #INC0708507 for the class CheckFederationID
* @author       : Sai Sampath 
*   Class       : CheckFederationID
* Modification Log 
* =======================================================================================
*   Ver     Date         Author          IncidentNo          Modification
*----------------------------------------------------------------------------------------
*   1.0     2-Mar-16    Sai Sampath     INC0708507          Initial Creation
*/
@isTest
public class CheckFederationIDTest
{
    static testMethod void CheckFedID()
    {  
        CheckFederationID checknew =  new CheckFederationID();
    }
}