/************************************************************************************************* 
* File Name  : CommunitiesSelfRegConfirmControllerTest
* Description: Test class for CommunitiesSelfRegConfirmController class
* Modification Log 
* ============================================================================= 
*   Date               Author                         Modification 
* ---------------------------------------------------------------------------------------
* 09-April-2018     Satish Maddhi(TCS)	  			Removed SeeAllData = true
*
*************************************************************************************************/
@IsTest public with sharing class CommunitiesSelfRegConfirmControllerTest {
    @IsTest 
    public static void testCommunitiesSelfRegConfirmController() {
        // Instantiate a new controller with all parameters in the page
        CommunitiesSelfRegConfirmController controller = new CommunitiesSelfRegConfirmController();
    }    
}