public without sharing class DTSFPART_CommonStrings {
    public static final String EMPTY_STRING = '';

    /* --- Record Type Names --- */
    public static final String PARTNER = 'Partner';
    public static final String CUSTOMER = 'Customer';
    
    /* --- Enterprise Permission Statuses --- */
    public static final String IN_PROGRESS = 'In Progress';
    public static final String COMPLETED = 'Completed';
    public static final String TRIGGER_STATUS = 'Trigger';
    public static final String RESYNC = 'Resync';
    public static final String ERROR = 'Error';

    /* --- C360 Response --- */
    public static final String SUCCESS = 'Success';

    /* --- Contact Status Values --- */
    public static final String INVITED = 'Invited';
    public static final String ACTIVE = 'Active';
    public static final String PENDING_ONBOARDING = 'Pending Onboarding';
    public static final String REGISTRATION_COMPLETED = 'Registration Completed';
    public static final String DEACTIVATION_REQUESTED = 'Deactivation Requested';

    /* --- Routes To Market --- */
    public static final String MR_LED = 'MR Led';
    public static final String MSI_LED = 'MSI Led';
    public static final String OPEN = 'Open';

    /* --- Permission Queueable Operations */
    public static final String CREATE_OPERATION = 'create';
    public static final String UPDATE_OPERATION = 'update';


}