/*  
 * Class Name  : LM_GlobalStaticVariables
 * Description:  This class is used to prevent firing trigger twice               
 * Modification Log 
 * ============================================================================= 
 * Ver   Date           Author        Modification 
 * -----------------------------------------------------------------------------------------------------------------------------------------
 * 1.0   02-Apr-13      Brahma        Initial Code
.
 */
public class LM_GlobalStaticVariables{
   
   public static boolean IS_LEAD_UPDATE_REQUIRED =true ;  
}